version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: bookmanagement_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mybookdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Bookmanagement@2025
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
